**Theory**

In [ ]:
### Q.1  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

ans)     ##NumPy (Numerical Python) is a library that enhances Python's capabilities for numerical operations, making it a fundamental package for scientific computing and data analysis. Its purpose is to provide support for large, multi-dimensional arrays and matrices, and to enable efficient numerical computations.

## Advantages of NumPy:

# 1. Efficient data storage: NumPy arrays require less memory and are faster to access than Python lists.
# 2. Vectorized operations: NumPy allows for element-wise operations on entire arrays, eliminating the need for loops.
# 3. Matrix operations: NumPy supports advanced matrix operations, such as linear algebra and random number generation.
# 4. High-performance computing: NumPy is optimized for performance, making it suitable for large-scale numerical computations.
# 5. Interoperability: NumPy arrays can be easily integrated with other popular scientific computing libraries, such as SciPy and Pandas.

## NumPy enhances Python's capabilities for numerical operations in several ways:

# 1. Speed: NumPy's vectorized operations and optimized C code make numerical computations much faster than using Python lists.
# 2. Convenience: NumPy provides a simple and intuitive API for performing complex numerical operations.
# 3. Flexibility: NumPy supports a wide range of data types and allows for easy conversion between them.
# 4. Integration: NumPy is widely adopted and integrates well with other scientific computing libraries and tools.

## By using NumPy, scientists and data analysts can:

# 1. Process large datasets: Efficiently handle and manipulate large datasets.
# 2. Perform complex calculations: Easily perform advanced numerical computations, such as linear algebra and signal processing.
# 3. Develop simulations: Create complex simulations, such as weather forecasting or fluid dynamics.
# 4. Analyze data: Quickly and easily analyze and visualize data using NumPy's integration with other libraries like Pandas and Matplotlib.

In [ ]:
### Q.2  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

ans)   ## NumPy's np.mean() and np.average() functions both calculate the average of an array, but they differ in their behavior and usage:

## np.mean():

# 1. Computes the arithmetic mean of the array elements.
# 2. Ignores NaN (Not a Number) values by default.
# 3. Has no weight parameter.

## np.average():

# 1. Computes the weighted average of the array elements.
# 2. Can handle NaN values by using the weights parameter.
# 3. Allows for specifying weights for each element.

## When to use each:

# 1. Use np.mean():
   #  - When you need the simple arithmetic mean.
   # - When your data doesn't contain NaN values or you want to ignore them.
# 2. Use np.average():
   #  - When you need a weighted average.
   # - When your data contains NaN values and you want to include them in the calculation using weights.
   # - When you want more control over the averaging process.

## In summary:

# - np.mean() is a simpler, more straightforward function for calculating the arithmetic mean.
# - np.average() provides more flexibility and control, especially when dealing with weighted averages or NaN values.

## Choose the function that best fits your specific use case and data requirements.

In [ ]:
### Q.3 Describe the methods for reversing a NumPy array along different axes. Provide examples for ID and 2D arrays.

ans)   ##  NumPy provides several methods to reverse an array along different axes:

# 1. np.flip(): Reverses the order of elements along the specified axis.

# 2. np.flipud(): Reverses the order of elements along the vertical axis (axis 0).

# 3. np.fliplr(): Reverses the order of elements along the horizontal axis (axis 1).

# 4. array[::-1]: Reverses the entire array using slicing.

## Examples:

# 1D Array:


import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_arr = np.flip(arr)
print(reversed_arr)  # Output: [5 4 3 2 1]


# 2D Array:


import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reverse the array along the vertical axis (axis 0)
reversed_arr_vert = np.flipud(arr)
print(reversed_arr_vert)  # Output: [[4 5 6]
                          #          [1 2 3]]

# Reverse the array along the horizontal axis (axis 1)
reversed_arr_horiz = np.fliplr(arr)
print(reversed_arr_horiz)  # Output: [[3 2 1]
                          #          [6 5 4]]

# Reverse the entire array
reversed_arr = arr[::-1, ::-1]
print(reversed_arr)  # Output: [[6 5 4]
                     #          [3 2 1]]


## In the 2D array examples, np.flipud() reverses the order of rows, np.fliplr() reverses the order of columns, and arr[::-1, ::-1] reverses both rows and columns.

In [ ]:
### Q.4 How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

ans)  ## To determine the data type of elements in a NumPy array, you can use the dtype attribute or the np.dtype() function:


import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Get the data type using the dtype attribute
print(arr.dtype)  # Output: int32

# Get the data type using np.dtype()
print(np.dtype(arr))  # Output: int32


## Data types are crucial in memory management and performance for several reasons:

# 1. Memory allocation: NumPy arrays store elements of the same data type, allowing for contiguous memory allocation. This leads to efficient memory usage and faster access times.
# 2. Memory usage: Different data types require varying amounts of memory. For example, float64 requires more memory than float32. Choosing the appropriate data type can significantly impact memory usage.
# 3. Performance: Certain operations are optimized for specific data types. For example, integer operations are generally faster than floating-point operations.
# 4. Type casting: When operating on arrays with different data types, NumPy may perform type casting, which can lead to performance overhead and potential data loss.
# 5. Array operations: Data types determine the behavior of array operations, such as arithmetic, comparison, and logical operations.

## Common NumPy data types include:

# - Integers: int8, int16, int32, int64
# - Floating-point numbers: float16, float32, float64
# - Complex numbers: complex64, complex128
# - Boolean: bool
# - Object: object (for storing arbitrary Python objects)

## By understanding and choosing the appropriate data type for your NumPy arrays, you can optimize memory usage, performance, and ensure accurate results.

In [ ]:
### Q.5 Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ans)   ## ndarrays (N-dimensional arrays)

## In NumPy, an ndarray (short for N-dimensional array) is a multi-dimensional array of fixed-size, homogeneous elements. It's the core data structure in NumPy, designed for efficient storage and manipulation of large datasets.

## Key features:

# 1. Multi-dimensional: ndarrays can have any number of dimensions (axes).
# 2. Fixed-size: The size of each dimension is fixed at creation time.
# 3. Homogeneous elements: All elements in an ndarray have the same data type.
# 4. Contiguous memory allocation: Elements are stored in contiguous memory blocks, enabling efficient access and manipulation.
# 5. Vectorized operations: ndarrays support element-wise operations, eliminating the need for loops.

## Differences from standard Python lists:

# 1. Homogeneity: Python lists can store elements of different data types, while ndarrays require homogeneous elements.
# 2. Fixed-size: Python lists can grow or shrink dynamically, whereas ndarrays have a fixed size.
# 3. Memory allocation: Python lists store elements as separate objects, leading to non-contiguous memory allocation. ndarrays store elements in contiguous memory blocks.
# 4. Performance: ndarrays are optimized for numerical computations and offer vectorized operations, making them much faster than Python lists for large datasets.
# 5. Additional functionality: ndarrays provide various methods and attributes for array manipulation, such as reshaping, indexing, and broadcasting.

## In summary, ndarrays are designed for efficient numerical computations and data manipulation, offering a more structured and optimized data structure than Python lists.

In [ ]:
### Q.6   Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

ans)  ## NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to:

# 1. Vectorized operations: NumPy arrays enable element-wise operations without loops, leveraging CPU's SIMD (Single Instruction, Multiple Data) capabilities.

# 2. Contiguous memory allocation: NumPy arrays store elements in contiguous memory blocks, reducing memory access overhead and improving cache performance.

# 3. Homogeneous data type: NumPy arrays ensure all elements have the same data type, reducing type checking and conversion overhead.

# 4. Optimized C code: NumPy's underlying C code is optimized for performance, providing a significant speed boost.

# 5. Parallelization: NumPy arrays can be easily parallelized using libraries like NumPy, SciPy, or joblib, further accelerating computations.

# 6. Reduced memory usage: NumPy arrays require less memory than Python lists, especially for large datasets.

# 7. Faster indexing and slicing: NumPy arrays offer faster indexing and slicing operations due to their contiguous memory layout.

# 8. Optimized linear algebra operations: NumPy arrays provide optimized implementations of linear algebra operations, such as matrix multiplication and eigenvalue decomposition.

### For large-scale numerical operations, NumPy arrays can be 10-100 times faster than Python lists. This performance difference grows with the size of the dataset, making NumPy arrays essential for scientific computing, data analysis, and machine learning applications.

## Here's a simple example demonstrating the performance difference:


import numpy as np
import time

# Create a large Python list and NumPy array
python_list = list(range(1000000))
numpy_array = np.arange(1000000)

# Measure the time taken for element-wise multiplication
start_time = time.time()
result_list = [x * 2 for x in python_list]
end_time = time.time()
print(f"Python list time: {end_time - start_time} seconds")

start_time = time.time()
result_array = numpy_array * 2
end_time = time.time()
print(f"NumPy array time: {end_time - start_time} seconds")


## This example shows that NumPy arrays can be significantly faster than Python lists for large-scale numerical operations.

In [ ]:
### Q.7   Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

ans)  ## NumPy's vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively.

## vstack()

# - Stacks arrays vertically (row-wise)
# - Creates a new array with the same number of columns as the input arrays
# - Input arrays must have the same shape except for the number of rows

## Example:


import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))
# Output:
# [[1 2 3]
#  [4 5 6]]


## hstack()

# - Stacks arrays horizontally (column-wise)
# - Creates a new array with the same number of rows as the input arrays
# - Input arrays must have the same shape except for the number of columns

## Example:


import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.hstack((a, b)))
# Output:
# [1 2 3 4 5 6]


## In summary:

# - vstack() stacks arrays vertically, adding rows.
# - hstack() stacks arrays horizontally, adding columns.

## Both functions are useful for combining arrays and creating larger datasets.

In [ ]:
### Q.8   Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

ans)  ## NumPy's fliplr() and flipud() methods are used to reverse the order of elements in an array along specific axes.

## fliplr()

# - Reverses the order of elements along the horizontal axis (axis 1)
# - Flips the array from left to right
# - Has no effect on the vertical axis (axis 0)

## Example:


import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.fliplr(arr))
# Output:
# [[3 2 1]
#  [6 5 4]]


## flipud()

# - Reverses the order of elements along the vertical axis (axis 0)
# - Flips the array from top to bottom
# - Has no effect on the horizontal axis (axis 1)

## Example:


import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.flipud(arr))
# Output:
# [[4 5 6]
#  [1 2 3]]


## In summary:

# - fliplr() reverses the order of elements along the horizontal axis (left to right)
# - flipud() reverses the order of elements along the vertical axis (top to bottom)

## These methods are useful for reversing the order of elements in arrays, which can be helpful in various applications such as image processing, data analysis, and more.

In [ ]:
### Q.9 Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

ans)   ##  NumPy's array_split() method splits an array into multiple sub-arrays along a specified axis. It's useful for dividing data into smaller chunks for processing or analysis.

## Functionality:

# - Splits an array into n sub-arrays along the specified axis
# - Returns a list of sub-arrays
# - Allows for splitting along any axis (default is axis 0)

## Handling uneven splits:

# - If the array cannot be evenly split, array_split() will create sub-arrays of varying sizes
# - The remaining elements will be distributed among the sub-arrays as evenly as possible
# - The last sub-array may have a different size than the others

## Example:


import numpy as np

arr = np.arange(10)
sub_arrays = np.array_split(arr, 3)

print(sub_arrays)
# Output:
# [array([0, 1, 2, 3]),
#  array([4, 5, 6, 7]),
#  array([8, 9])]


## In this example, the array is split into 3 sub-arrays along axis 0. The first two sub-arrays have 4 elements each, while the last sub-array has 2 elements.



In [ ]:
### Q.10  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

ans)   ### Vectorization and broadcasting are fundamental concepts in NumPy that enable efficient array operations.

## Vectorization

## Vectorization refers to the ability to perform operations on entire arrays at once, without the need for explicit loops. This is achieved through NumPy's universal functions (ufuncs), which are designed to work with arrays. Vectorization allows for:

# - Element-wise operations (e.g., addition, multiplication)
# - Matrix operations (e.g., matrix multiplication)
# - Reduction operations (e.g., sum, mean)

## Vectorization eliminates the need for loops, making code more concise, readable, and efficient.

## Broadcasting

## Broadcasting is a mechanism that allows arrays with different shapes to be combined in operations. It enables arrays to be "broadcast" to a compatible shape, allowing for operations to be performed element-wise. Broadcasting rules:

# - If arrays have the same shape, no broadcasting is needed
# - If arrays have different shapes, NumPy tries to broadcast them to a compatible shape
# - Arrays with size 1 in a particular dimension can be broadcast to any size in that dimension

## Broadcasting enables operations between arrays with different shapes, making it a powerful feature for efficient array operati

## Vectorization and broadcasting contribute to efficient array operations in several ways:

# - Speed: Vectorized operations are faster than explicit loops, as they leverage optimized C code and CPU instructions.
# - Memory efficiency: Broadcasting reduces memory usage by avoiding unnecessary array copies.
# - Code simplicity: Vectorization and broadcasting enable concise, readable code, reducing development time and errors.
# - Flexibility: Broadcasting allows for operations between arrays with different shapes, making it a versatile feature for various applications.

## By combining vectorization and broadcasting, NumPy enables efficient, flexible, and expressive array operations, making it a powerful tool for scientific computing, data analysis, and machine learning.

**Practical**

In [ ]:
### Q.1 Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

ans)   ## Here's how we can create a 3x3 NumPy array with random integers between 1 and 100 and then interchange its rows and columns:


import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(arr)

# Interchange rows and columns (transpose the array)
transposed_arr = arr.T
print("\nTransposed array:")
print(transposed_arr)


## In this code:

# 1. We import the NumPy library.
# 2. We create a 3x3 NumPy array arr with random integers between 1 and 100 using np.random.randint.
# 3. We print the original array.
# 4. We interchange the rows and columns of the original array by taking its transpose using the .T attribute, storing the result in transposed_arr.
# 5. We print the transposed array.



In [ ]:
### Q.2  Generate a ID NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

ans)    Here's how we can generate a 1D NumPy array with 10 elements, reshape it into a 2x5 array, and then into a 5x2 array:


import numpy as np

# Generate a 1D NumPy array with 10 elements
arr = np.arange(1, 11)
print("Original 1D array:")
print(arr)

# Reshape the array into a 2x5 array
arr_2x5 = arr.reshape(2, 5)
print("\nReshaped 2x5 array:")
print(arr_2x5)

# Reshape the array into a 5x2 array
arr_5x2 = arr.reshape(5, 2)
print("\nReshaped 5x2 array:")
print(arr_5x2)


## In this code:

# 1. We import the NumPy library.
# 2. We generate a 1D NumPy array arr with 10 elements using np.arange.
# 3. We print the original 1D array.
# 4. We reshape the array into a 2x5 array using the reshape method, storing the result in arr_2x5.
# 5. We print the reshaped 2x5 array.
# 6. We reshape the array into a 5x2 array using the reshape method again, storing the result in arr_5x2.
# 7. We print the reshaped 5x2 array.



In [ ]:
### Q.3  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

ans)  ##   Here's how we can create a 4x4 NumPy array with random float values and add a border of zeros around it, resulting in a 6x6 array:


import numpy as np

# Create a 4x4 NumPy array with random float values
arr = np.random.rand(4, 4)
print("Original 4x4 array:")
print(arr)

# Add a border of zeros around the array, resulting in a 6x6 array
arr_with_border = np.pad(arr, 1, mode='constant')
print("\n6x6 array with border of zeros:")
print(arr_with_border)


## In this code:

# 1. We import the NumPy library.
# 2. We create a 4x4 NumPy array arr with random float values using np.random.rand.
# 3. We print the original 4x4 array.
# 4. We add a border of zeros around the array using the np.pad function, storing the result in arr_with_border. The pad_width argument is set to 1, which means a border of width 1 is added around the array. The mode argument is set to 'constant', which means the border is filled with a constant value (zero in this case).
# 5. We print the 6x6 array with the border of zeros.


In [ ]:
### Q.4   Using NumPy, create an array of integers from 10 to 60 with a step of 5.

ans) ##  Here's how we can create an array of integers from 10 to 60 with a step of 5 using NumPy:


import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)
print(arr)


## In this code:

# 1. We import the NumPy library.
# 2. We use the np.arange function to create an array of integers. The arguments are:
    # - start: The starting value (10).
    # - stop: The ending value (61, which is exclusive, so we use 61 to include 60).
    # - step: The step size (5).
# 3. We print the resulting array.

## Output:


[10 15 20 25 30 35 40 45 50 55 60]




In [ ]:
### Q.5   Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

ans)  ##  Here's how we can create a NumPy array of strings and apply different case transformations to each element:


import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = arr.upper()
lowercase = arr.lower()
title_case = arr.title()
capitalize = arr.capitalize()

print("Original array:")
print(arr)
print("\nUppercase:")
print(uppercase)
print("\nLowercase:")
print(lowercase)
print("\nTitle case:")
print(title_case)
print("\nCapitalize:")
print(capitalize)


## In this code:

# 1. We import the NumPy library.
# 2. We create a NumPy array arr with the strings 'python', 'numpy', and 'pandas'.
# 3. We apply different case transformations using the following methods:
    # - upper(): Converts all characters to uppercase.
    # - lower(): Converts all characters to lowercase.
    # - title(): Converts the first character of each word to uppercase and the rest to lowercase.
    # - capitalize(): Converts the first character to uppercase and the rest to lowercase.
# 4. We print the original array and the transformed arrays.

## Output:


# Original array:
['python' 'numpy' 'pandas']

# Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

# Lowercase:
['python' 'numpy' 'pandas']

# Title case:
['Python' 'Numpy' 'Pandas']

# apitalize:
['Python' 'Numpy' 'Pandas']


In [ ]:
### Q.6  Generate a NumPy array of words. Insert a space between each character of every word in the array.

ans)   ##  Here's how we can generate a NumPy array of words and insert a space between each character of every word:


import numpy as np

# Generate a NumPy array of words
words = np.array(['hello', 'world', 'numpy', 'array'])

# Insert a space between each character of every word
spaced_words = np.char.array([list(word) for word in words])
spaced_words = spaced_words.join(' ')

print(spaced_words)


## In this code:

# 1. We import the NumPy library.
# 2. We generate a NumPy array words with the words 'hello', 'world', 'numpy', and 'array'.
# 3. We use a list comprehension to split each word into individual characters and store them in a new array spaced_words.
# 4. We use the join method to insert a space between each character of every word.
# 5. We print the resulting array spaced_words.

## Output:


['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']




In [ ]:
### Q.7   Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

ans)   ##  Here's how we can create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division:


import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Perform element-wise operations
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nElement-wise addition:")
print(addition)
print("\nElement-wise subtraction:")
print(subtraction)
print("\nElement-wise multiplication:")
print(multiplication)
print("\nElement-wise division:")
print(division)


## In this code:

# 1. We import the NumPy library.
# 2. We create two 2D NumPy arrays arr1 and arr2.
# 3. We perform element-wise operations using the corresponding operators:
    #- + for addition
    #- - for subtraction
    #- * for multiplication
   # - / for division
# 4. We print the original arrays and the results of the element-wise operations.

#3 Output:


# Array 1:
[[1 2]
 [3 4]]

# Array 2:
[[5 6]
 [7 8]]

# Element-wise addition:
[[ 6  8]
 [10 12]]

# Element-wise subtraction:
[[-4 -4]
 [-4 -4]]

# Element-wise multiplication:
[[ 5 12]
 [21 32]]

# Element-wise division:
[[0.2 0.33333333]
 [0.42857143 0.5]]


In [ ]:
### Q.8   Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

ans)   ##   Here's how  can create a 5x5 identity matrix using NumPy and extract its diagonal elements:


import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


## In this code:

# 1. We import the NumPy library.
# 2. We create a 5x5 identity matrix using np.eye(5).
# 3. We print the identity matrix.
# 4. We extract the diagonal elements using np.diag().
# 5. We print the diagonal elements.

## Output:


# 5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

# Diagonal Elements:
[1. 1. 1. 1. 1.]


In [ ]:
### Q.9  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

ans)     ##  Here's how we can generate a NumPy array of 100 random integers between 0 and 1000 and find and display all prime numbers in this array:


import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)
print("Random Array:")
print(random_array)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    max_divisor = int(np.sqrt(n)) + 1
    for d in range(3, max_divisor, 2):
        if n % d == 0:
            return False
    return True

# Find and display all prime numbers in the array
prime_numbers = random_array[np.vectorize(is_prime)(random_array)]
print("\nPrime Numbers:")
print(prime_numbers)


## In this code:

# 1. We import the NumPy library.
# 2. We generate a NumPy array random_array with 100 random integers between 0 and 1000 using np.random.randint.
# 3. We print the random array.
# 4. We define a function is_prime to check if a number is prime.
# 5. We use np.vectorize to apply the is_prime function to each element of the array and get a boolean mask.
# 6. We use the boolean mask to index into the original array and get the prime numbers.
# 7. We print the prime numbers.



In [ ]:
### Q.10   Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

ans)    ## Here's how we can create a NumPy array representing daily temperatures for a month and calculate and display the weekly averages:


import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.uniform(20, 30, size=30)
print("Daily Temperatures:")
print(daily_temperatures)

# Calculate weekly averages
weekly_temperatures = [daily_temperatures[i:i+7].mean() for i in range(0, 30, 7)]
print("\nWeekly Averages:")
print(weekly_temperatures)


## In this code:

# 1. We import the NumPy library.
# 2. We create a NumPy array daily_temperatures with 30 random temperatures between 20 and 30 using np.random.uniform.
# 3. We print the daily temperatures.
# 4. We calculate the weekly averages by slicing the array into 7-day chunks and taking the mean of each chunk using a list comprehension.
# 5. We print the weekly averages.



## Output:


# Daily Temperatures:
[23.14391522 24.65403547 26.19344489 25.89249144 22.47547824 28.43851748
 27.65376144 24.82394951 26.91199048 25.47785414 23.65548158 28.59494314
 27.04219482 26.65403547 25.89249144 24.14391522 23.14391522 26.19344489
 25.47785414 28.43851748 27.65376144 26.91199048 24.82394951 25.89249144
 27.04219482 23.65548158 28.59494314 26.65403547 25.47785414 24.14391522]

# Weekly Averages:
[25.33333333 26.04761905 25.69230769 25.57142857 25.80952381]


## his output shows the daily temperatures and the weekly averages for the month.